### ISSUE TITLE
Issue with contracts on stocking

### ISSUE THREAD

**Issue by xenon007** [flyingferret/seat-whtools#2]
/whtools/stocking
`in WHToolsController.php line 70
at HandleExceptions->handleError(8, 'compact(): Undefined variable: contracts', '/var/www/seat/vendor/flyingferret/seat-whtools/src/Http/Controllers/WHToolsController.php', 70, array('stock' => array(), 'fitlist' => array(array('id' => 1, 'shiptype' => 'Jackdaw', 'fitname' => 'Stargate (Minmatar)', 'typeID' => 34828), array('id' => 2, 'shiptype' => 'Manticore', 'fitname' => 'Manticore', 'typeID' => 12032), array('id' => 3, 'shiptype' => 'Tengu', 'fitname' => 'Tengu', 'typeID' => 29984), array('id' => 4, 'shiptype' => 'Basilisk', 'fitname' => 'Basilisk', 'typeID' => 11985), array('id' => 5, 'shiptype' => 'Scythe', 'fitname' => 'Scythe', 'typeID' => 631), array('id' => 7, 'shiptype' => 'Crow', 'fitname' => 'Crow', 'typeID' => 11176), array('id' => 8, 'shiptype' => 'Nestor', 'fitname' => 'Nestor DRG 2019', 'typeID' => 33472), array('id' => 9, 'shiptype' => 'Oneiros', 'fitname' => '*CTA +3pg', 'typeID' => 11989), array('id' => 10, 'shiptype' => 'Nestor', 'fitname' => 'бюджет', 'typeID' => 33472), array('id' => 11, 'shiptype' => 'Zarmazd', 'fitname' => 'Zarmazd VOLTA', 'typeID' => 49713), array('id' => 12, 'shiptype' => 'Leshak', 'fitname' => 'Leshak DRG NEW', 'typeID' => 47271), array('id' => 13, 'shiptype' => 'Drekavac', 'fitname' => 'бонус флот', 'typeID' => 49711), array('id' => 14, 'shiptype' => 'Nestor', 'fitname' => 'Nestor DRG 2019', 'typeID' => 33472), array('id' => 15, 'shiptype' => 'Bhaalgorn', 'fitname' => 'Baal Leshak', 'typeID' => 17920), array('id' => 16, 'shiptype' => 'Leshak', 'fitname' => 'Leshak', 'typeID' => 47271), array('id' => 17, 'shiptype' => 'Drekavac', 'fitname' => 'бонус флот', 'typeID' => 49711), array('id' => 18, 'shiptype' => 'Nestor', 'fitname' => 'Nestor DRG 2019', 'typeID' => 33472), array('id' => 19, 'shiptype' => 'Bhaalgorn', 'fitname' => 'Support BSH', 'typeID' => 17920), array('id' => 20, 'shiptype' => 'Bhaalgorn', 'fitname' => 'DRG support ', 'typeID' => 17920), array('id' => 21, 'shiptype' => 'Scorpion', 'fitname' => 'Scorpion Лешак', 'typeID' => 640), array('id' => 22, 'shiptype' => 'Drekavac', 'fitname' => 'Drekavac', 'typeID' => 49711), array('id' => 23, 'shiptype' => 'Huginn', 'fitname' => 'CTA', 'typeID' => 11961), array('id' => 24, 'shiptype' => 'Huginn', 'fitname' => 'CTA MVD', 'typeID' => 11961), array('id' => 25, 'shiptype' => 'Lachesis', 'fitname' => 'CTA', 'typeID' => 11971), array('id' => 26, 'shiptype' => 'Lachesis', 'fitname' => 'CTA', 'typeID' => 11971), array('id' => 27, 'shiptype' => 'Armageddon', 'fitname' => 'RR', 'typeID' => 643), array('id' => 28, 'shiptype' => 'Dominix', 'fitname' => 'RR', 'typeID' => 645), array('id' => 29, 'shiptype' => 'Scorpion', 'fitname' => 'RR', 'typeID' => 640), array('id' => 30, 'shiptype' => 'Prophecy', 'fitname' => 'RR/CT Prophecy ', 'typeID' => 16233), array('id' => 31, 'shiptype' => 'Prophecy', 'fitname' => 'T2', 'typeID' => 16233), array('id' => 32, 'shiptype' => 'Jackdaw', 'fitname' => 'Джек 2019', 'typeID' => 34828),array('id' => 33, 'shiptype' => 'Kirin', 'fitname' => 'Roum Dragon', 'typeID' => 37458), array('id' => 34, 'shiptype' => 'Scalpel', 'fitname' => 'Scalpel - роум 1', 'typeID' => 37460), array('id' => 35, 'shiptype' => 'Bantam', 'fitname' => 'Bantam', 'typeID' => 582), array('id' => 36, 'shiptype' => 'Bifrost', 'fitname' => 'бонус', 'typeID' => 37480), array('id' => 37, 'shiptype' => 'Stork', 'fitname' => 'бонус', 'typeID' => 37482), array('id' => 38, 'shiptype' => 'Phoenix', 'fitname' => 'Phoenix CTA Active', 'typeID' => 19726), array('id' => 39, 'shiptype' => 'Minokawa', 'fitname' => 'Minokawa CTA 2016 v2', 'typeID' => 37605), array('id' => 40, 'shiptype' => 'Apostle', 'fitname' => 'Apostle fit', 'typeID' => 37604), array('id' => 41, 'shiptype' => 'Revelation', 'fitname' => 'Revelation CTA aktiv', 'typeID' => 19720), array('id' => 42, 'shiptype' => 'Naglfar', 'fitname' => 'Naglfar CTA aktiv', 'typeID' => 19722), array('id' => 43, 'shiptype' => 'Moros', 'fitname' => 'Moros CTA aktiv', 'typeID' => 19724))))
at compact('fitlist', 'stock', 'contracts')in WHToolsController.php line 70`
Can't understand how it

**Comment by flyingferret** [comment]
Ok there was an undefined varible in the getStockingView() return statement.  Please try updating to version 0.0.19.  Glad someone other than me is using this lol.

**Comment by xenon007** [comment]
Thanks you
