### ISSUE TITLE
blue loot sales totals errors out

### ISSUE THREAD

**Issue by dstevens79** [flyingferret/seat-whtools#7]
I get this error on blue loot sales totals : 
https://i.imgur.com/Il1ggx4.png

**Comment by veteranmina** [comment]
@dstevens79 I would confirm if you have installed the plugin fully. However, can you provide any logs for this when it happens?

**Comment by flyingferret** [comment]
Removing BlueLoot tools for  now for a complete rework if people want it still.  Currently not very used that I know of.
